algoritmo "semnome"
// Faça um programa usando a estrutura “para” que leia um número inteiro
// positivo e mostre na tela uma contagem de 0 até o valor digitado:
// Ex: Digite um valor: 9
// Contagem: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, FIM!
var
N,I: inteiro
inicio
      Escreva("É para contar até quanto: ")
      Leia(N)
      Para I <- 0 Ate N Faca
           Escreva(I,",")
      FimPara
      Escreva(" FIM!")
fimalgoritmo
