algoritmo "Exercicio"
//Ex:11)     Desenvolva uma lógica que leia os valores de A, B e C de uma equação do
//           segundo grau e mostre o valor de Delta.
var
a, b, c, delta: real
inicio

      Escreva("Informe o valor de A: ")
      Leia (a)
      Escreva("Informe o valor de B: ")
      Leia (b)
      Escreva("Informe o valor de C: ")
      Leia (c)
      delta <- (b^2)-4*(a*c)
      Escreva("O Valor de Delta é:",delta)
fimalgoritmo
