algoritmo "semnome"
// Faça um programa que leia 7 números inteiros e no final mostre o somatório
// entre eles.
var
I, soma, num:inteiro
inicio
      I <- 1
      soma <- 0
      Enquanto (I <= 7 )Faca
               Escreva("Informe um número inteiro: ")
               Leia(num)
               soma <- soma + num
               I <- I + 1
      FimEnquanto
      Escreval()
      Escreval("A soma dos números informados é: ",soma)
      Escreval()
fimalgoritmo
